#!/usr/bin/env bash
# Provisions the "CalmAI: What's Working" PostHog dashboard with 7 insight tiles.
# Idempotent: re-running creates a new dashboard with a timestamped name so you
# can iterate without polluting your project.
#
# Required env:
#   POSTHOG_PERSONAL_API_KEY  — phx_... key from PostHog → Account → Personal API Keys
#                                Must have "insight:write" and "dashboard:write" scopes.
#   POSTHOG_PROJECT_ID        — numeric project ID (find in PostHog URL: /project/<ID>/)
#
# Optional env:
#   POSTHOG_HOST              — defaults to https://us.i.posthog.com (use eu.i.posthog.com for EU)
#
# Requires: bash, curl, jq (install jq via `brew install jq` on macOS)
#
# Usage:
#   POSTHOG_PERSONAL_API_KEY=phx_... POSTHOG_PROJECT_ID=12345 ./scripts/setup-posthog-dashboard.sh

set -euo pipefail

# ---- Preflight ------------------------------------------------------------

: "${POSTHOG_PERSONAL_API_KEY:?Set POSTHOG_PERSONAL_API_KEY (phx_... from PostHog → Account → Personal API Keys)}"
: "${POSTHOG_PROJECT_ID:?Set POSTHOG_PROJECT_ID (numeric project ID from PostHog URL)}"
POSTHOG_HOST="${POSTHOG_HOST:-https://us.i.posthog.com}"

command -v jq >/dev/null 2>&1 || { echo "jq is required. Install with: brew install jq"; exit 1; }
command -v curl >/dev/null 2>&1 || { echo "curl is required."; exit 1; }

API="$POSTHOG_HOST/api/projects/$POSTHOG_PROJECT_ID"
AUTH_HEADER="Authorization: Bearer $POSTHOG_PERSONAL_API_KEY"
TIMESTAMP=$(date +%Y%m%d-%H%M)
DASHBOARD_NAME="CalmAI: What's Working ($TIMESTAMP)"

echo "→ Provisioning PostHog dashboard at $POSTHOG_HOST"
echo "  Project: $POSTHOG_PROJECT_ID"
echo "  Name:    $DASHBOARD_NAME"
echo

# ---- Helpers --------------------------------------------------------------

# POST a JSON payload to a PostHog endpoint; returns the .id of the created resource.
posthog_post() {
  local path="$1"
  local body="$2"
  local label="$3"
  local response
  response=$(curl -sS -w "\n%{http_code}" -X POST "$API$path" \
    -H "$AUTH_HEADER" \
    -H "Content-Type: application/json" \
    -d "$body")
  local http_code=$(echo "$response" | tail -n1)
  local json=$(echo "$response" | sed '$d')
  if [[ "$http_code" != "201" && "$http_code" != "200" ]]; then
    echo "✗ $label failed (HTTP $http_code):"
    echo "$json" | jq . 2>/dev/null || echo "$json"
    exit 1
  fi
  echo "$json" | jq -r '.id'
}

# ---- Create dashboard ------------------------------------------------------

DASHBOARD_ID=$(posthog_post "/dashboards/" "$(jq -n \
  --arg name "$DASHBOARD_NAME" \
  --arg desc "Daily founder dashboard — onboarding funnel, feature usage, conversion, app health, latency. Generated by scripts/setup-posthog-dashboard.sh" \
  '{name: $name, description: $desc, pinned: true}')" \
  "Dashboard")
echo "✓ Dashboard #$DASHBOARD_ID"

# Wrapper that creates an insight pre-attached to the dashboard.
create_insight() {
  local name="$1"
  local description="$2"
  local filters="$3"
  local body=$(jq -n \
    --arg name "$name" \
    --arg desc "$description" \
    --argjson filters "$filters" \
    --argjson dashboards "[$DASHBOARD_ID]" \
    '{name: $name, description: $desc, filters: $filters, dashboards: $dashboards}')
  local id=$(posthog_post "/insights/" "$body" "Insight '$name'")
  echo "✓ #$id  $name"
}

echo

# ---- Card 1: Onboarding → Trial Funnel ------------------------------------

create_insight \
  "1. Onboarding → Trial Funnel" \
  "Where users drop off between first app open and tapping 'Start my 3 days'. Healthy: 8–15% hero→pricing_completed. Breakdown by media_source to compare TikTok vs Meta." \
  '{
    "insight": "FUNNELS",
    "events": [
      {"id": "onboarding_hero_viewed", "type": "events", "order": 0},
      {"id": "onboarding_nickname_submitted", "type": "events", "order": 1},
      {"id": "onboarding_confirm_cta_tapped", "type": "events", "order": 2},
      {"id": "signin_completed", "type": "events", "order": 3},
      {"id": "paywall_soft_viewed", "type": "events", "order": 4},
      {"id": "paywall_pricing_viewed", "type": "events", "order": 5},
      {"id": "paywall_pricing_completed", "type": "events", "order": 6}
    ],
    "date_from": "-28d",
    "funnel_window_interval": 1,
    "funnel_window_interval_unit": "day"
  }'

# ---- Card 2: Daily Active by Feature --------------------------------------

create_insight \
  "2. Daily Active by Feature" \
  "Which features are touched each day. Chat should be 60–70% of total feature DAU; if breathe/ground/journal eclipse chat for >3 days, core value prop isn't landing." \
  '{
    "insight": "TRENDS",
    "events": [
      {"id": "chat_message_sent", "type": "events", "math": "dau", "order": 0},
      {"id": "breathe_started", "type": "events", "math": "dau", "order": 1},
      {"id": "ground_started", "type": "events", "math": "dau", "order": 2},
      {"id": "journal_entry_saved", "type": "events", "math": "dau", "order": 3},
      {"id": "mood_logged", "type": "events", "math": "dau", "order": 4}
    ],
    "date_from": "-28d",
    "interval": "day",
    "display": "ActionsBar"
  }'

# ---- Card 3: Trial Start Rate ---------------------------------------------

create_insight \
  "3. Trial Start Rate" \
  "Of users who saw pricing, what % completed checkout. Healthy: 30–45% with a free-trial offer. If it drops, check paywall_purchase_failed broken down by error_category." \
  '{
    "insight": "FUNNELS",
    "events": [
      {"id": "paywall_pricing_viewed", "type": "events", "order": 0},
      {"id": "paywall_pricing_completed", "type": "events", "order": 1}
    ],
    "date_from": "-28d",
    "funnel_viz_type": "steps",
    "funnel_window_interval": 1,
    "funnel_window_interval_unit": "hour"
  }'

# ---- Card 4: Crash-Free Session Rate --------------------------------------

create_insight \
  "4. Crash-Free Session Rate (%)" \
  "Healthy: >99.5%. If it drops, open Sentry, filter to last 24h, group by release. Formula = (app_start_complete - unhandled_error) / app_start_complete × 100." \
  '{
    "insight": "TRENDS",
    "events": [
      {"id": "app_start_complete", "type": "events", "math": "unique_session", "order": 0},
      {"id": "unhandled_error", "type": "events", "math": "unique_session", "order": 1}
    ],
    "formula": "(A - B) / A * 100",
    "date_from": "-28d",
    "interval": "day",
    "display": "ActionsLineGraph"
  }'

# ---- Card 5: Chat Time-to-First-Token (p50 / p95) -------------------------

create_insight \
  "5. Chat Time-to-First-Token (ms)" \
  "How long users wait for the AI to start replying. Healthy: p50 <1500ms, p95 <4000ms. If p95 spikes without an error spike, the model provider is slow." \
  '{
    "insight": "TRENDS",
    "events": [
      {"id": "chat_first_token_received", "type": "events", "math": "p50", "math_property": "latency_ms", "order": 0, "custom_name": "p50"},
      {"id": "chat_first_token_received", "type": "events", "math": "p95", "math_property": "latency_ms", "order": 1, "custom_name": "p95"}
    ],
    "date_from": "-28d",
    "interval": "day",
    "display": "ActionsLineGraph"
  }'

# ---- Card 6: Notification Tap-Through Engagement --------------------------

create_insight \
  "6. Notification Tap-Through → Chat" \
  "Of users who tapped a notification, what % sent a chat within 1 hour? Healthy: 60%+. If <40%, notifications open the app but don't land on relevant content." \
  '{
    "insight": "FUNNELS",
    "events": [
      {"id": "notification_tapped", "type": "events", "order": 0},
      {"id": "chat_message_sent", "type": "events", "order": 1}
    ],
    "date_from": "-28d",
    "funnel_window_interval": 1,
    "funnel_window_interval_unit": "hour"
  }'

# ---- Card 7: Trial → Paid Conversion --------------------------------------

create_insight \
  "7. Trial → Paid Conversion" \
  "Of trials started, how many convert to paid. Healthy: 35–50% on iOS mental-health. Source-of-truth: subscription_trial_converted from RevenueCat webhook. Breakdown by media_source for ROAS per channel." \
  '{
    "insight": "FUNNELS",
    "events": [
      {"id": "subscription_trial_started", "type": "events", "order": 0},
      {"id": "subscription_trial_converted", "type": "events", "order": 1}
    ],
    "date_from": "-60d",
    "funnel_window_interval": 14,
    "funnel_window_interval_unit": "day"
  }'

echo
echo "✓ Dashboard ready: $POSTHOG_HOST/project/$POSTHOG_PROJECT_ID/dashboard/$DASHBOARD_ID"
echo
echo "Next steps:"
echo "  1. Open the dashboard URL above."
echo "  2. Drag the tiles into the order you want — the API doesn't set positions."
echo "  3. In each tile's Breakdown control, add 'media_source' to slice by TikTok/Meta/organic."
echo "  4. Pin the dashboard so it's the team's home page."
echo
echo "If a tile shows 'No data', that event has not fired yet. Check:"
echo "  - PostHog → Activity → Live events (events should appear within seconds of trigger)"
echo "  - EXPO_PUBLIC_POSTHOG_API_KEY is set in .env"
echo "  - The app has been opened on a device after the rebuild"
